"""The run id. Regenerated by recovery so a client's {run, seq} gap check resets."""
import uuid

_current_run_id = ""


def new_run_id() -> str:
    return uuid.uuid4().hex


def current_run_id() -> str:
    return _current_run_id


def set_run_id(run: str) -> None:
    global _current_run_id
    _current_run_id = run
